name: Deploy to cluster
on: [ push ]
jobs:
  TestedJob:
    name: "Action: cache - hashFiles"
    runs-on: docker.home.arpa/venthe/ubuntu-runner:22.10
    steps:
      - uses: actions/cache@main
        with:
          path: |
            path/to/dependencies
            some/other/dependencies
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
  TestedJob:
    name: "Action: upload-artifact"
    runs-on: docker.home.arpa/venthe/ubuntu-runner:22.10
    steps:
      - uses: actions/checkout@v3
      - name: Restore cached Primes
        id: cache-primes-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            path/to/dependencies
            some/other/dependencies
          key: ${{ runner.os }}-primes
      - name: Save Primes
        id: cache-primes-save
        uses: actions/cache/save@v3
        with:
          path: |
            path/to/dependencies
            some/other/dependencies
          key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}
  TestedJob:
    name: "Action: upload-artifact"
    runs-on: docker.home.arpa/venthe/ubuntu-runner:22.10
    steps:
      - uses: actions/checkout@v3
      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@main
        with:
          path: prime-numbers
          key: ${{ runner.os }}-primes
      - name: Generate Prime Numbers
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: /generate-primes.sh -d prime-numbers
      - name: Use Prime Numbers
        run: /primes.sh -d prime-numbers
